"""Shared SQLAlchemy column helpers (cd-xma93).

Currently exports :class:`UtcDateTime` — a ``TypeDecorator`` wrapping
``DateTime(timezone=True)`` that guarantees every read returns a
**tz-aware UTC** :class:`datetime.datetime`, regardless of dialect.

Why this exists
---------------

SQLite has no native timezone-aware timestamp type. SQLAlchemy's
``DateTime(timezone=True)`` accepts aware datetimes on write but
returns **naive** values on read for SQLite — the tzinfo is silently
dropped on the round-trip. Pydantic v2 then serialises those as
``"2026-05-02T19:20:43.161127"`` (no ``Z`` / ``+00:00`` suffix), which
violates the OpenAPI ``format: date-time`` (RFC 3339) constraint and
turns up as 31 "Response violates schema" failures under the identity
schemathesis sweep (cd-xma93). Postgres' ``TIMESTAMP WITH TIME ZONE``
returns aware values, so the bug is SQLite-only — but the fix is
trivially correct for both backends.

Write-side semantics
--------------------

This decorator **attaches UTC** to naive inputs on write
(``process_bind_param``). The alternative — rejecting naive with
``TypeError`` — would surface every legacy caller that still hands a
naive ``datetime.utcnow()`` to a mapper as a 5xx in production. The
project standard is "Time is UTC at rest" (``AGENTS.md`` §"Application-
specific notes"), so attaching UTC to naive writes *preserves the
caller's intent* (they meant UTC) while still normalising the
on-disk representation. Aware non-UTC inputs are converted to UTC.

Read-side semantics
-------------------

If the dialect returns a naive datetime (SQLite), tzinfo is set to
``UTC``. Aware values pass through unchanged (Postgres path).

Alembic / autogen
-----------------

``impl = DateTime(timezone=True)`` and ``cache_ok = True`` make the
type render identically to a plain ``DateTime(timezone=True)`` column
in autogenerated migrations and SQLAlchemy's compiled-statement cache.
``compare_type=True`` in ``migrations/env.py`` sees the same
underlying column type, so existing migrations are unaffected.
"""

from __future__ import annotations

from datetime import UTC, datetime
from typing import Any

from sqlalchemy import DateTime
from sqlalchemy.engine import Dialect
from sqlalchemy.types import TypeDecorator

__all__ = ["UtcDateTime"]


class UtcDateTime(TypeDecorator[datetime]):
    """``DateTime(timezone=True)`` that round-trips as aware UTC.

    Reads always return tz-aware UTC. Writes accept naive datetimes
    (UTC is attached) or aware datetimes in any zone (converted to
    UTC). ``None`` is preserved on both sides.
    """

    impl = DateTime(timezone=True)
    cache_ok = True

    @property
    def python_type(self) -> type[datetime]:
        return datetime

    def process_bind_param(
        self, value: datetime | None, dialect: Dialect
    ) -> datetime | None:
        if value is None:
            return None
        if value.tzinfo is None:
            # Naive in -> attach UTC. Documented choice (cd-xma93):
            # the caller meant UTC ("Time is UTC at rest"); this keeps
            # legacy ``datetime.utcnow()`` writes working without a
            # repo-wide audit while still normalising on-disk shape.
            return value.replace(tzinfo=UTC)
        return value.astimezone(UTC)

    def process_result_value(
        self, value: datetime | None, dialect: Dialect
    ) -> datetime | None:
        if value is None:
            return None
        if value.tzinfo is None:
            # SQLite path: dialect drops tzinfo on read. Re-attach UTC
            # so pydantic v2 serialises with the RFC 3339 ``+00:00``
            # suffix and ``DateTime(timezone=True)`` columns behave
            # identically across dialects.
            return value.replace(tzinfo=UTC)
        return value

    def __repr__(self) -> str:
        return "UtcDateTime()"

    # ``copy`` is used by SQLAlchemy when cloning Column objects (e.g.
    # ``Column.copy()`` for inherited mappers). Default TypeDecorator
    # ``copy`` does the right thing (no instance state), but we
    # override the signature explicitly to satisfy ``mypy --strict``
    # against ``TypeDecorator`` 's untyped baseline.
    def copy(self, **kwargs: Any) -> UtcDateTime:
        return UtcDateTime()
