import {
  AirVent,
  AlarmClock,
  AlarmSmoke,
  Armchair,
  Baby,
  BadgeCheck,
  Bath,
  Bed,
  Bell,
  BedDouble,
  Bike,
  Biohazard,
  Blinds,
  Bolt,
  Brush,
  BrushCleaning,
  Bug,
  Building2,
  Bus,
  Cable,
  Camera,
  Car,
  CarFront,
  ChefHat,
  CircleParking,
  ClipboardCheck,
  Clock,
  Coffee,
  CookingPot,
  DoorClosed,
  DoorOpen,
  Drill,
  Droplets,
  Dumbbell,
  Fan,
  Fence,
  FireExtinguisher,
  Flame,
  Flashlight,
  Flower2,
  Fuel,
  Gauge,
  Hammer,
  HardHat,
  Heater,
  Home,
  House,
  KeyRound,
  Lamp,
  Landmark,
  Laptop,
  Leaf,
  Lightbulb,
  LockKeyhole,
  Luggage,
  Mail,
  MapPin,
  Microwave,
  Monitor,
  Package,
  PackageCheck,
  PaintBucket,
  Paintbrush,
  ParkingMeter,
  Phone,
  Plug,
  PlugZap,
  Refrigerator,
  Route,
  Router,
  Scissors,
  ShieldCheck,
  ShowerHead,
  Snowflake,
  Sofa,
  Sparkles,
  SprayCan,
  Sprout,
  Sun,
  Thermometer,
  ThermometerSun,
  Toilet,
  Trash2,
  Trees,
  Truck,
  Tv,
  Utensils,
  Vault,
  Waves,
  WavesLadder,
  WashingMachine,
  Wifi,
  Wind,
  Wrench,
  Zap,
  type LucideIcon,
} from "lucide-react";

type LazyIconModule = { default: LucideIcon };
type LazyIconLoader = () => Promise<LazyIconModule>;

// §14 "Icons": data fields store a Lucide icon name (PascalCase)
// and the web resolves them through this curated catalog. Unknown
// names fall back to the generic Package glyph so stale data never
// breaks the render.
const EAGER_ASSET_ICON_REGISTRY = {
  AirVent,
  AlarmClock,
  AlarmSmoke,
  Armchair,
  Baby,
  BadgeCheck,
  Bath,
  Bed,
  Bell,
  BedDouble,
  Bike,
  Biohazard,
  Blinds,
  Bolt,
  Brush,
  BrushCleaning,
  Bug,
  Building2,
  Bus,
  Cable,
  Camera,
  Car,
  CarFront,
  ChefHat,
  CircleParking,
  ClipboardCheck,
  Clock,
  Coffee,
  CookingPot,
  DoorClosed,
  DoorOpen,
  Drill,
  Droplets,
  Dumbbell,
  Fan,
  Fence,
  FireExtinguisher,
  Flame,
  Flashlight,
  Flower2,
  Fuel,
  Gauge,
  Hammer,
  HardHat,
  Heater,
  Home,
  House,
  KeyRound,
  Lamp,
  Landmark,
  Laptop,
  Leaf,
  Lightbulb,
  LockKeyhole,
  Luggage,
  Mail,
  MapPin,
  Microwave,
  Monitor,
  Package,
  PackageCheck,
  PaintBucket,
  Paintbrush,
  ParkingMeter,
  Phone,
  Plug,
  PlugZap,
  Refrigerator,
  Route,
  Router,
  Scissors,
  ShieldCheck,
  ShowerHead,
  Snowflake,
  Sofa,
  Sparkles,
  SprayCan,
  Sprout,
  Sun,
  Thermometer,
  ThermometerSun,
  Toilet,
  Trash2,
  Trees,
  Truck,
  Tv,
  Utensils,
  Vault,
  Waves,
  WavesLadder,
  WashingMachine,
  Wifi,
  Wind,
  Wrench,
  Zap,
} satisfies Record<string, LucideIcon>;
type EagerAssetIconName = keyof typeof EAGER_ASSET_ICON_REGISTRY;

export const ASSET_ICON_LOADERS = {
  AirVent: loadEagerIcon("AirVent"),
  AlarmClock: loadEagerIcon("AlarmClock"),
  AlarmSmoke: loadEagerIcon("AlarmSmoke"),
  Armchair: loadEagerIcon("Armchair"),
  Baby: loadEagerIcon("Baby"),
  BadgeCheck: loadEagerIcon("BadgeCheck"),
  Bath: loadEagerIcon("Bath"),
  Bed: loadEagerIcon("Bed"),
  BedDouble: loadEagerIcon("BedDouble"),
  Bell: loadEagerIcon("Bell"),
  Bike: loadEagerIcon("Bike"),
  Biohazard: loadEagerIcon("Biohazard"),
  Blinds: loadEagerIcon("Blinds"),
  Bolt: loadEagerIcon("Bolt"),
  Brush: loadEagerIcon("Brush"),
  BrushCleaning: loadEagerIcon("BrushCleaning"),
  Bug: loadEagerIcon("Bug"),
  Building2: loadEagerIcon("Building2"),
  Bus: loadEagerIcon("Bus"),
  Cable: loadEagerIcon("Cable"),
  Camera: loadEagerIcon("Camera"),
  Car: loadEagerIcon("Car"),
  CarFront: loadEagerIcon("CarFront"),
  ChefHat: loadEagerIcon("ChefHat"),
  CircleParking: loadEagerIcon("CircleParking"),
  ClipboardCheck: loadEagerIcon("ClipboardCheck"),
  Clock: loadEagerIcon("Clock"),
  Coffee: loadEagerIcon("Coffee"),
  CookingPot: loadEagerIcon("CookingPot"),
  DoorClosed: loadEagerIcon("DoorClosed"),
  DoorOpen: loadEagerIcon("DoorOpen"),
  Drill: loadEagerIcon("Drill"),
  Droplets: loadEagerIcon("Droplets"),
  Dumbbell: loadEagerIcon("Dumbbell"),
  Fan: loadEagerIcon("Fan"),
  Fence: loadEagerIcon("Fence"),
  FireExtinguisher: loadEagerIcon("FireExtinguisher"),
  Flame: loadEagerIcon("Flame"),
  Flashlight: loadEagerIcon("Flashlight"),
  Flower2: loadEagerIcon("Flower2"),
  Fuel: loadEagerIcon("Fuel"),
  Gauge: loadEagerIcon("Gauge"),
  Hammer: loadEagerIcon("Hammer"),
  HardHat: loadEagerIcon("HardHat"),
  Heater: loadEagerIcon("Heater"),
  Home: loadEagerIcon("Home"),
  House: loadEagerIcon("House"),
  KeyRound: loadEagerIcon("KeyRound"),
  Lamp: loadEagerIcon("Lamp"),
  Landmark: loadEagerIcon("Landmark"),
  Laptop: loadEagerIcon("Laptop"),
  Leaf: loadEagerIcon("Leaf"),
  Lightbulb: loadEagerIcon("Lightbulb"),
  LockKeyhole: loadEagerIcon("LockKeyhole"),
  Luggage: loadEagerIcon("Luggage"),
  Mail: loadEagerIcon("Mail"),
  MapPin: loadEagerIcon("MapPin"),
  Microwave: loadEagerIcon("Microwave"),
  Monitor: loadEagerIcon("Monitor"),
  Package: loadEagerIcon("Package"),
  PackageCheck: loadEagerIcon("PackageCheck"),
  PaintBucket: loadEagerIcon("PaintBucket"),
  Paintbrush: loadEagerIcon("Paintbrush"),
  ParkingMeter: loadEagerIcon("ParkingMeter"),
  Phone: loadEagerIcon("Phone"),
  Plug: loadEagerIcon("Plug"),
  PlugZap: loadEagerIcon("PlugZap"),
  Refrigerator: loadEagerIcon("Refrigerator"),
  Route: loadEagerIcon("Route"),
  Router: loadEagerIcon("Router"),
  Scissors: loadEagerIcon("Scissors"),
  ShieldCheck: loadEagerIcon("ShieldCheck"),
  ShowerHead: loadEagerIcon("ShowerHead"),
  Snowflake: loadEagerIcon("Snowflake"),
  Sofa: loadEagerIcon("Sofa"),
  Sparkles: loadEagerIcon("Sparkles"),
  SprayCan: loadEagerIcon("SprayCan"),
  Sprout: loadEagerIcon("Sprout"),
  Sun: loadEagerIcon("Sun"),
  Thermometer: loadEagerIcon("Thermometer"),
  ThermometerSun: loadEagerIcon("ThermometerSun"),
  Toilet: loadEagerIcon("Toilet"),
  Trash2: loadEagerIcon("Trash2"),
  Trees: loadEagerIcon("Trees"),
  Truck: loadEagerIcon("Truck"),
  Tv: loadEagerIcon("Tv"),
  Utensils: loadEagerIcon("Utensils"),
  Vault: loadEagerIcon("Vault"),
  WashingMachine: loadEagerIcon("WashingMachine"),
  Waves: loadEagerIcon("Waves"),
  WavesLadder: loadEagerIcon("WavesLadder"),
  Wifi: loadEagerIcon("Wifi"),
  Wind: loadEagerIcon("Wind"),
  Wrench: loadEagerIcon("Wrench"),
  Zap: loadEagerIcon("Zap"),
} satisfies Record<string, LazyIconLoader>;

export const ASSET_ICON_REGISTRY = EAGER_ASSET_ICON_REGISTRY;

export type AssetIconName = keyof typeof ASSET_ICON_LOADERS;

export const ASSET_ICON_NAMES: readonly AssetIconName[] = Object.freeze(
  (Object.keys(ASSET_ICON_LOADERS) as AssetIconName[]).sort(),
);

export function isAssetIconName(name: string | null | undefined): name is AssetIconName {
  return Boolean(name && hasOwn(ASSET_ICON_LOADERS, name));
}

function loadEagerIcon(name: EagerAssetIconName): LazyIconLoader {
  return () => Promise.resolve({ default: EAGER_ASSET_ICON_REGISTRY[name] });
}

function hasOwn<T extends object>(object: T, key: PropertyKey): key is keyof T {
  return Object.prototype.hasOwnProperty.call(object, key);
}
