export const graph = {
  providers: [
    {
      id: "prov_openrouter",
      name: "OpenRouter",
      provider_type: "openrouter",
      endpoint: "https://openrouter.ai/api/v1",
      api_key_ref: "env:OPENROUTER_API_KEY",
      api_key_status: "present",
      default_model: null,
      requests_per_minute: 60,
      timeout_s: 60,
      priority: 0,
      is_enabled: true,
      provider_model_count: 3,
    },
  ],
  models: [
    {
      id: "model_gemma",
      canonical_name: "google/gemma-4-31b-it",
      display_name: "Gemma 4 31B IT",
      vendor: "Google",
      capabilities: ["chat", "json_mode", "function_calling"],
      context_window: 128000,
      max_output_tokens: 8192,
      price_source: "openrouter",
      price_source_model_id: "google/gemma-4-31b-it",
      is_active: true,
      notes: null,
      provider_model_count: 1,
    },
    {
      id: "model_text",
      canonical_name: "test/text-only",
      display_name: "Text Only",
      vendor: "test",
      capabilities: ["chat"],
      context_window: 32000,
      max_output_tokens: null,
      price_source: "manual",
      price_source_model_id: null,
      is_active: true,
      notes: null,
      provider_model_count: 1,
    },
    {
      id: "model_fast",
      canonical_name: "test/fast-chat",
      display_name: "Fast Chat",
      vendor: "test",
      capabilities: ["chat", "function_calling"],
      context_window: 64000,
      max_output_tokens: null,
      price_source: "manual",
      price_source_model_id: null,
      is_active: true,
      notes: null,
      provider_model_count: 1,
    },
  ],
  provider_models: [
    {
      id: "pm_gemma",
      provider_id: "prov_openrouter",
      model_id: "model_gemma",
      api_model_id: "google/gemma-4-31b-it",
      input_cost_per_million: 0.15,
      output_cost_per_million: 0.2,
      max_tokens_override: null,
      temperature_override: null,
      supports_system_prompt: true,
      supports_temperature: true,
      reasoning_effort: "",
      price_source_override: "",
      price_last_synced_at: "2026-04-30T12:00:00Z",
      is_enabled: true,
    },
    {
      id: "pm_text",
      provider_id: "prov_openrouter",
      model_id: "model_text",
      api_model_id: "test/text-only",
      input_cost_per_million: 0,
      output_cost_per_million: 0,
      max_tokens_override: null,
      temperature_override: null,
      supports_system_prompt: true,
      supports_temperature: true,
      reasoning_effort: "",
      price_source_override: "none",
      price_last_synced_at: null,
      is_enabled: true,
    },
    {
      id: "pm_fast",
      provider_id: "prov_openrouter",
      model_id: "model_fast",
      api_model_id: "test/fast-chat",
      input_cost_per_million: 0,
      output_cost_per_million: 0,
      max_tokens_override: null,
      temperature_override: null,
      supports_system_prompt: true,
      supports_temperature: true,
      reasoning_effort: "",
      price_source_override: "none",
      price_last_synced_at: null,
      is_enabled: true,
    },
  ],
  capabilities: [
    {
      key: "chat.manager",
      description: "Owner/manager-side embedded chat agent",
      required_capabilities: ["chat", "function_calling"],
    },
    {
      key: "voice.transcribe",
      description: "Turn a voice note into text",
      required_capabilities: ["audio_input"],
    },
  ],
  inheritance: [],
  assignments: [
    {
      id: "assign_chat_manager",
      capability: "chat.manager",
      description: "Owner/manager-side embedded chat agent",
      priority: 0,
      provider_model_id: "pm_gemma",
      max_tokens: null,
      temperature: null,
      extra_api_params: {},
      required_capabilities: ["chat", "function_calling"],
      is_enabled: true,
      last_used_at: null,
      spend_usd_30d: 1.25,
      calls_30d: 12,
    },
  ],
  assignment_issues: [],
  totals: {
    spend_usd_30d: 1.25,
    calls_30d: 12,
    provider_count: 1,
    model_count: 3,
    capability_count: 2,
    unassigned_capabilities: ["voice.transcribe"],
  },
};

export const calls = [
  {
    at: "2026-04-30T12:00:00Z",
    capability: "chat.manager",
    model_id: "google/gemma-4-31b-it",
    input_tokens: 100,
    output_tokens: 40,
    cost_cents: 3,
    latency_ms: 420,
    status: "ok",
    assignment_id: "assign_chat_manager",
    provider_model_id: "pm_gemma",
    prompt_template_id: null,
    prompt_version: null,
    fallback_attempts: 0,
    raw_response_available: false,
  },
];

export const prompts = [
  {
    id: "prompt_chat_manager",
    capability: "chat.manager",
    name: "Manager chat",
    version: 3,
    is_active: true,
    is_customised: false,
    default_hash: "abc123",
    updated_at: "2026-04-30T12:00:00Z",
    revisions_count: 2,
    preview: "You are the manager assistant.",
  },
];
